import type { PortalObjectDef } from "@/lib/portal/types";

export const CLINICAL_SETTINGS: PortalObjectDef = {
  key: "clinical_settings",
  label: "Clinical settings",
  icon: "sliders",
  description:
    "Clinically governed thresholds. Rules read approved values only; sign-off needs clinical.settings.manage.",
  table: "clinical_settings",
  titleColumn: "label",
  sourceAirtable: "appH2jHpsNR1nqEQ2.tbl69r1kelxG4g93L",
  readPerm: "portal.clinical_settings.read",
  writePerm: "clinical.settings.manage",
  sort: 60,
  allowCreate: false,
  allowDelete: false,
  defaultSort: [{ field: "category", dir: "asc" }],
  searchColumns: ["key", "label", "owner"],
  columns: [
    { key: "label", label: "Parameter", type: "text", required: true, maxLength: 300 },
    { key: "key", label: "Key", type: "text", readOnly: true },
    {
      key: "category",
      label: "Category",
      type: "select",
      readOnly: true,
      options: [
        { value: "paediatrics", label: "Paediatrics" },
        { value: "gp_adults", label: "GP / adults" },
        { value: "gynaecology", label: "Gynaecology" },
        { value: "medication_sequence", label: "Medication sequence" },
        { value: "escalation", label: "Escalation" },
        { value: "operational", label: "Operational" },
        { value: "recall", label: "Recall" },
        { value: "engine", label: "Engine" },
      ],
    },
    {
      key: "value_type",
      label: "Value type",
      type: "select",
      readOnly: true,
      defaultHidden: true,
      options: [
        { value: "text", label: "Text" },
        { value: "number", label: "Number" },
        { value: "boolean", label: "Yes / no" },
        { value: "json", label: "JSON" },
        { value: "list", label: "List" },
      ],
    },
    { key: "proposed_value", label: "Proposed", type: "text" },
    { key: "approved_value", label: "Approved", type: "text" },
    { key: "live_value", label: "Live today", type: "text", readOnly: true, defaultHidden: true },
    {
      key: "sign_off_status",
      label: "Sign-off",
      type: "select",
      required: true,
      options: [
        { value: "blocking", label: "Blocking" },
        { value: "awaiting", label: "Awaiting" },
        { value: "confirm_exclusion", label: "Confirm exclusion" },
        { value: "approved", label: "Approved" },
      ],
    },
    { key: "owner", label: "Owner", type: "text", maxLength: 120 },
    { key: "signed_by", label: "Signed by", type: "text", maxLength: 120 },
    { key: "signed_at", label: "Signed on", type: "date" },
    { key: "notes", label: "Notes", type: "long_text", defaultHidden: true },
    { key: "source", label: "Source", type: "text", readOnly: true, defaultHidden: true },
  ],
};
