import type { PortalObjectDef } from "@/lib/portal/types";

const AT_UNITE = "app7QJ2pvhADHQeBP";
const AT_ACUTE = "appH2jHpsNR1nqEQ2";

export const REF_CONDITION_GROUPS: PortalObjectDef = {
  key: "ref_condition_groups",
  label: "Condition groups",
  icon: "layers",
  description:
    "Chronic condition groups used by recall programmes. Mental-health groups are never messaged.",
  table: "ref_condition_groups",
  titleColumn: "name",
  sourceAirtable: `${AT_UNITE}.tblZqf4Zcw5Kweadh`,
  readPerm: "portal.ref_condition_groups.read",
  writePerm: "portal.ref_condition_groups.write",
  sort: 20,
  allowCreate: true,
  allowDelete: false,
  defaultSort: [{ field: "sort", dir: "asc" }],
  searchColumns: ["key", "name"],
  columns: [
    { key: "name", label: "Name", type: "text", required: true, maxLength: 200 },
    { key: "key", label: "Key", type: "text", required: true, createOnly: true, maxLength: 60 },
    { key: "messageable", label: "Messageable", type: "boolean" },
    { key: "sort", label: "Priority", type: "number", integer: true },
    { key: "follow_up_interval_days", label: "Follow-up (days)", type: "number", integer: true },
    {
      key: "regular_medication_examples",
      label: "Medication examples",
      type: "long_text",
      defaultHidden: true,
    },
    {
      key: "monitoring_labs_cpt",
      label: "Monitoring labs (CPT)",
      type: "text",
      defaultHidden: true,
    },
    {
      key: "monitoring_procedures_cpt",
      label: "Monitoring procedures (CPT)",
      type: "text",
      defaultHidden: true,
    },
    { key: "typical_visit_cpt", label: "Typical visit (CPT)", type: "text", defaultHidden: true },
  ],
};

export const REF_DIAGNOSES: PortalObjectDef = {
  key: "ref_diagnoses",
  label: "Diagnoses (ICD-10)",
  icon: "stethoscope",
  description:
    "ICD-10 reference list. Chronic flags and condition groups drive recall eligibility.",
  table: "ref_diagnoses",
  titleColumn: "code",
  sourceAirtable: `${AT_UNITE}.tblZqf4Zcw5Kweadh`,
  readPerm: "portal.ref_diagnoses.read",
  writePerm: "portal.ref_diagnoses.write",
  sort: 10,
  allowCreate: true,
  allowDelete: false,
  defaultSort: [{ field: "code", dir: "asc" }],
  searchColumns: ["code", "short_description", "long_description"],
  columns: [
    { key: "code", label: "Code", type: "text", required: true, createOnly: true, maxLength: 20 },
    { key: "short_description", label: "Short description", type: "text", maxLength: 500 },
    { key: "long_description", label: "Long description", type: "long_text", defaultHidden: true },
    { key: "chronic", label: "Chronic", type: "boolean" },
    { key: "top30", label: "Top 30", type: "boolean" },
    {
      key: "condition_group_id",
      label: "Condition group",
      type: "link",
      link: { object: "ref_condition_groups" },
    },
    {
      key: "not_found_in_unite",
      label: "Not found in Unite",
      type: "boolean",
      defaultHidden: true,
    },
  ],
};

export const REF_MEDICATIONS: PortalObjectDef = {
  key: "ref_medications",
  label: "Medications",
  icon: "pill",
  description: "Unite medication catalogue keyed on the DDC / local code.",
  table: "ref_medications",
  titleColumn: "trade_name",
  sourceAirtable: `${AT_UNITE}.tblLM2BXjA680GQws`,
  readPerm: "portal.ref_medications.read",
  writePerm: "portal.ref_medications.write",
  sort: 30,
  allowCreate: true,
  allowDelete: false,
  defaultSort: [{ field: "trade_name", dir: "asc" }],
  searchColumns: ["ddc_code", "trade_name", "scientific_name"],
  columns: [
    {
      key: "ddc_code",
      label: "DDC code",
      type: "text",
      required: true,
      createOnly: true,
      maxLength: 60,
    },
    { key: "trade_name", label: "Trade name", type: "text", maxLength: 300 },
    { key: "scientific_name", label: "Scientific name", type: "text", maxLength: 500 },
    { key: "strength", label: "Strength", type: "text", maxLength: 100 },
    { key: "dosage_form", label: "Dosage form", type: "text", maxLength: 100 },
    { key: "route", label: "Route", type: "text", maxLength: 100 },
    { key: "status", label: "Status", type: "text", maxLength: 60, defaultHidden: true },
    { key: "scientific_code", label: "Scientific code", type: "text", defaultHidden: true },
    { key: "package_price", label: "Package price", type: "number", defaultHidden: true },
    { key: "granular_unit", label: "Granular unit", type: "text", defaultHidden: true },
    { key: "registered_owner", label: "Registered owner", type: "text", defaultHidden: true },
    { key: "source_updated_on", label: "Source updated", type: "date", defaultHidden: true },
    { key: "source", label: "Source", type: "text", defaultHidden: true },
    { key: "is_ebp", label: "EBP", type: "boolean", defaultHidden: true },
    {
      key: "medicine_type",
      label: "Medicine type",
      type: "text",
      defaultHidden: true,
      description: "Advisory only — never used to classify (classify by code).",
    },
    {
      key: "all_medicine_types",
      label: "All medicine types",
      type: "multi_select",
      defaultHidden: true,
    },
    { key: "icd_codes", label: "ICD codes", type: "text", defaultHidden: true },
  ],
};

export const REF_ITEMS: PortalObjectDef = {
  key: "ref_items",
  label: "Items & tests",
  icon: "flask",
  description:
    "Unite items and the CPT master. Tick “doctor verified” before a code is used in live automations.",
  table: "ref_items",
  titleColumn: "code",
  sourceAirtable: `${AT_UNITE}.tblTJtk6aIMbwpoA2`,
  readPerm: "portal.ref_items.read",
  writePerm: "portal.ref_items.write",
  sort: 40,
  allowCreate: true,
  allowDelete: false,
  defaultSort: [{ field: "code", dir: "asc" }],
  searchColumns: ["code", "description"],
  columns: [
    { key: "code", label: "Code", type: "text", required: true, createOnly: true, maxLength: 60 },
    { key: "description", label: "Description", type: "text", maxLength: 500 },
    { key: "item_type", label: "Type", type: "text", maxLength: 60 },
    { key: "test_category", label: "Test category", type: "text", maxLength: 120 },
    { key: "patient_message_group", label: "Patient message group", type: "text", maxLength: 120 },
    { key: "doctor_verified", label: "Doctor verified", type: "boolean" },
  ],
};

export const REF_MEDICATION_CLASSES: PortalObjectDef = {
  key: "ref_medication_classes",
  label: "Medication classes",
  icon: "tag",
  description:
    "Drug class by Unite local code. Unknown or unclassified codes fail closed: no sequence fires.",
  table: "ref_medication_classes",
  titleColumn: "unite_local_code",
  sourceAirtable: `${AT_ACUTE}.tblIxa5xUOG3GRwmt`,
  readPerm: "portal.ref_medication_classes.read",
  writePerm: "portal.medication_classes.write",
  sort: 50,
  allowCreate: true,
  allowDelete: false,
  defaultSort: [{ field: "unite_local_code", dir: "asc" }],
  searchColumns: ["unite_local_code", "medication_name"],
  columns: [
    {
      key: "unite_local_code",
      label: "Unite local code",
      type: "text",
      required: true,
      createOnly: true,
      maxLength: 60,
    },
    { key: "medication_name", label: "Medication", type: "text", maxLength: 300 },
    {
      key: "class",
      label: "Class",
      type: "select",
      required: true,
      options: [
        { value: "antibiotic", label: "Antibiotic" },
        { value: "steroid", label: "Steroid" },
        { value: "probiotic", label: "Probiotic" },
        { value: "supplement", label: "Supplement" },
        { value: "enzyme", label: "Enzyme" },
        { value: "other", label: "Other" },
        { value: "unclassified", label: "Unclassified" },
      ],
    },
    { key: "requires_probiotics_default", label: "Probiotics by default", type: "boolean" },
    {
      key: "classified_by",
      label: "Classified by",
      type: "text",
      maxLength: 120,
      description: "'heuristic' is a suggestion only and must stay unclassified.",
    },
    { key: "classified_at", label: "Classified at", type: "datetime", defaultHidden: true },
    { key: "notes", label: "Notes", type: "long_text", defaultHidden: true },
  ],
};
