/**
 * pnpm audit:security — static security pass over the repo (Phase 11).
 * Prints findings and writes docs/audit/security-pass.generated.md (a table of every
 * server action / route handler with its guard, mutation and audit-log status).
 * The same rules run in CI as tests/unit/security-static.test.ts.
 */
import fs from "node:fs";
import path from "node:path";

import {
  analyzeFile,
  clientLeaks,
  sensitiveLogs,
  type FileReport,
} from "../lib/security/static-audit";
import { AUDIT_EXEMPT, AUTHN_ONLY_OK, UNGUARDED_OK } from "../lib/security/policy";

const ROOT = process.cwd();
const SKIP = new Set(["node_modules", ".next", ".git", "tests", "supabase"]);

export function walk(dir: string, out: string[] = []): string[] {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (SKIP.has(e.name)) continue;
    const full = path.join(dir, e.name);
    if (e.isDirectory()) walk(full, out);
    else if (/\.(ts|tsx)$/.test(e.name)) out.push(full);
  }
  return out;
}

export function scanRepo(root = ROOT) {
  const files = ["app", "lib", "components", "middleware.ts"]
    .map((p) => path.join(root, p))
    .filter((p) => fs.existsSync(p))
    .flatMap((p) => (fs.statSync(p).isDirectory() ? walk(p) : [p]));
  const reports: FileReport[] = [];
  const leaks: string[] = [];
  const logs: string[] = [];
  for (const f of files) {
    const rel = path.relative(root, f).replaceAll(path.sep, "/");
    const src = fs.readFileSync(f, "utf8");
    const r = analyzeFile(rel, src);
    if (r) reports.push(r);
    leaks.push(...clientLeaks(rel, src));
    logs.push(...sensitiveLogs(rel, src));
  }
  return { reports, leaks, logs };
}

function main() {
  const { reports, leaks, logs } = scanRepo();
  const rows = reports.flatMap((r) => r.entries);
  const lines = [
    "# Security pass — generated static audit",
    "",
    `Generated by \`pnpm audit:security\`. ${rows.length} entry points in ${reports.length} modules.`,
    "",
    "| File | Entry point | Guard | Mutates | audit_log |",
    "|---|---|---|---|---|",
    ...rows.map((e) => {
      const k = `${e.file}::${e.name}`;
      const guard = e.authz
        ? "permission (`can`/`requirePerm`)"
        : e.authn
          ? `authn only — ${AUTHN_ONLY_OK[k] ?? UNGUARDED_OK[k] ?? "**UNREVIEWED**"}`
          : UNGUARDED_OK[k]
            ? `none — ${UNGUARDED_OK[k]}`
            : "**NONE**";
      const audit = !e.mutates ? "—" : e.audited ? "yes" : AUDIT_EXEMPT[k] ? `exempt — ${AUDIT_EXEMPT[k]}` : "**no**";
      return `| ${e.file} | \`${e.name}\` | ${guard} | ${e.mutates ? "yes" : "—"} | ${audit} |`;
    }),
    "",
    `Client-bundle leaks: ${leaks.length === 0 ? "none" : "\n" + leaks.map((l) => `- ${l}`).join("\n")}`,
    "",
    `Sensitive-looking log arguments: ${logs.length === 0 ? "none" : "\n" + logs.map((l) => `- ${l}`).join("\n")}`,
    "",
  ];
  const out = path.join(ROOT, "docs/audit/security-pass.generated.md");
  fs.writeFileSync(out, lines.join("\n"));
  const unguarded = rows.filter((e) => !e.authz && !e.authn && !UNGUARDED_OK[`${e.file}::${e.name}`]);
  console.log(`${rows.length} entry points; ${unguarded.length} unguarded and unreviewed; report → ${path.relative(ROOT, out)}`);
  for (const e of unguarded) console.log(`  UNGUARDED ${e.file} ${e.name}`);
  if (leaks.length || logs.length) {
    for (const l of [...leaks, ...logs]) console.log(`  ${l}`);
    process.exitCode = 1;
  }
}

if (process.argv[1]?.endsWith("audit-security.ts")) main();
